services:
  frontend:
    labels:
      - traefik.enable=true
      - traefik.docker.network=sns-network
      - traefik.http.routers.frontend.entryPoints=web
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
      - traefik.http.services.frontend.loadbalancer.server.port=3000
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: frontend
    restart: always
networks:
  default:
    name: sns-network