const domainConsts = {
  MIN_USERNAME_LENGTH: 4,
  MAX_USERNAME_LENGTH: 16,

  MIN_DISPLAY_NAME_LENGTH: 1,
  MAX_DISPLAY_NAME_LENGTH: 32,

  MAX_BIOGRAPHY_LENGTH: 256,

  ICON_IMAGE_WIDTH: 256,
  ICON_IMAGE_HEIGHT: 256,

  BG_IMAGE_WIDTH: 960,
  BG_IMAGE_HEIGHT: 320,
};

export default domainConsts;
