export const publicEnv = {
  BASE_URL: process.env["NEXT_PUBLIC_BASE_URL"],
  API_URL: process.env["NEXT_PUBLIC_API_URL"],
  IMAGE_URL: process.env["NEXT_PUBLIC_IMAGE_URL"],

  FIREBASE_API_KEY: process.env["NEXT_PUBLIC_FIREBASE_API_KEY"],
  FIREBASE_AUTH_DOMAIN: process.env["NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"],
  FIREBASE_PROJECT_ID: process.env["NEXT_PUBLIC_FIREBASE_PROJECT_ID"],
  FIREBASE_STORAGE_BUCKET: process.env["NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"],
  FIREBASE_MESSAGING_SENDER_ID: process.env["NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"],
  FIREBASE_APP_ID: process.env["NEXT_PUBLIC_FIREBASE_APP_ID"],
  FIREBASE_MEASUREMENT_ID: process.env["NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"],
};
